# Generated by Django 3.2.6 on 2021-08-06 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourbooking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_parent', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CategoryTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provincial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourbooking.district')),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
                ('content', models.TextField(max_length=1000, null=True)),
                ('time_open', models.TimeField()),
                ('time_close', models.TimeField()),
                ('date_add', models.TimeField(auto_now_add=True)),
                ('date_update', models.TimeField(auto_now=True)),
                ('image', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('hotline', models.CharField(max_length=10, null=True)),
                ('lat', models.CharField(max_length=100, null=True)),
                ('lng', models.CharField(max_length=100, null=True)),
                ('views', models.IntegerField()),
                ('category_travel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourbooking.categorytravel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourbooking.ward')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
                ('hotline', models.CharField(max_length=10, null=True)),
                ('content', models.TextField(max_length=1000, null=True)),
                ('date_add', models.TimeField(auto_now_add=True)),
                ('date_update', models.TimeField(auto_now=True)),
                ('time_open', models.TimeField()),
                ('time_close', models.TimeField()),
                ('image', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('lat', models.CharField(max_length=100, null=True)),
                ('lng', models.CharField(max_length=100, null=True)),
                ('views', models.IntegerField()),
                ('price_min', models.FloatField(null=True)),
                ('price_max', models.FloatField(null=True)),
                ('category_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourbooking.categoryservice')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourbooking.ward')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000, null=True)),
                ('date_add', models.TimeField(auto_now_add=True)),
                ('date_update', models.TimeField(auto_now=True)),
                ('travel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourbooking.travel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000, null=True)),
                ('date_add', models.TimeField(auto_now_add=True)),
                ('date_update', models.TimeField(auto_now=True)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourbooking.service')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('views', models.IntegerField()),
                ('status', models.BooleanField()),
                ('content', models.TextField(max_length=1000, null=True)),
                ('date_add', models.TimeField(auto_now_add=True)),
                ('date_update', models.TimeField(auto_now=True)),
                ('image', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImagesTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100, null=True)),
                ('date_add', models.TimeField(auto_now_add=True)),
                ('date_update', models.TimeField(auto_now=True)),
                ('travel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourbooking.travel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImagesService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100, null=True)),
                ('date_add', models.TimeField(auto_now_add=True)),
                ('date_update', models.TimeField(auto_now=True)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourbooking.service')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='provincial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourbooking.provincial'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000, null=True)),
                ('date_add', models.TimeField(auto_now_add=True)),
                ('date_update', models.TimeField(auto_now=True)),
                ('news', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourbooking.news')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
