# Generated by Django 3.2.6 on 2021-08-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourbooking', '0004_auto_20210808_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesservice',
            name='image',
            field=models.ImageField(default=None, upload_to='images/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='imagestravel',
            name='image',
            field=models.ImageField(default=None, upload_to='images/%Y/%m'),
        ),
    ]
