# Generated by Django 3.2.6 on 2021-08-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourbooking', '0005_auto_20210808_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default=None, upload_to='images/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(default=None, upload_to='images/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='image',
            field=models.ImageField(default=None, upload_to='images/%Y/%m'),
        ),
    ]
