# Generated by Django 3.2.6 on 2021-08-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourbooking', '0006_auto_20210808_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='service',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price_max',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price_min',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='lng',
        ),
        migrations.AddField(
            model_name='travel',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
