# Generated by Django 3.2.6 on 2021-08-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourbooking', '0007_auto_20210808_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='ward',
            name='district',
        ),
        migrations.RemoveField(
            model_name='service',
            name='user',
        ),
        migrations.RemoveField(
            model_name='service',
            name='ward',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='ward',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Provincial',
        ),
        migrations.DeleteModel(
            name='Ward',
        ),
    ]
