# Generated by Django 3.2.6 on 2021-08-08 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourbooking', '0008_auto_20210808_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
                ('hotline', models.CharField(max_length=10, null=True)),
                ('content', models.TextField(max_length=1000, null=True)),
                ('date_add', models.TimeField(auto_now_add=True)),
                ('date_update', models.TimeField(auto_now=True)),
                ('time_open', models.TimeField()),
                ('time_close', models.TimeField()),
                ('image', models.ImageField(default=None, upload_to='images/%Y/%m')),
                ('address', models.CharField(max_length=100, null=True)),
                ('views', models.IntegerField()),
                ('time', models.CharField(max_length=100, null=True)),
                ('traffic', models.CharField(max_length=100, null=True)),
                ('category_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourbooking.categoryhotel')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourbooking.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImagesHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='images/%Y/%m')),
                ('date_add', models.TimeField(auto_now_add=True)),
                ('date_update', models.TimeField(auto_now=True)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourbooking.hotel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000, null=True)),
                ('date_add', models.TimeField(auto_now_add=True)),
                ('date_update', models.TimeField(auto_now=True)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourbooking.hotel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='imagesservice',
            name='service',
        ),
        migrations.RemoveField(
            model_name='imagesservice',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reviewservice',
            name='service',
        ),
        migrations.RemoveField(
            model_name='reviewservice',
            name='user',
        ),
        migrations.RemoveField(
            model_name='service',
            name='category_service',
        ),
        migrations.AddField(
            model_name='travel',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourbooking.location'),
        ),
        migrations.AddField(
            model_name='travel',
            name='time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='traffic',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='CategoryService',
        ),
        migrations.DeleteModel(
            name='ImagesService',
        ),
        migrations.DeleteModel(
            name='ReviewService',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
