# Generated by Django 3.2.6 on 2021-08-08 13:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourbooking', '0009_auto_20210808_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='travel',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
