# Generated by Django 3.2.6 on 2021-08-12 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourbooking', '0012_auto_20210810_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField(default=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='district',
            name='provincial',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='category_hotel',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='district',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='location',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='provincial',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='ward',
        ),
        migrations.RemoveField(
            model_name='imageshotel',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='imageshotel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='imagestravel',
            name='travel',
        ),
        migrations.RemoveField(
            model_name='imagestravel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reviewhotel',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='reviewhotel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='district',
        ),
        migrations.AddField(
            model_name='travel',
            name='detail_location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='CategoryHotel',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='ImagesHotel',
        ),
        migrations.DeleteModel(
            name='ImagesTravel',
        ),
        migrations.DeleteModel(
            name='Provincial',
        ),
        migrations.DeleteModel(
            name='ReviewHotel',
        ),
        migrations.DeleteModel(
            name='Ward',
        ),
        migrations.AddField(
            model_name='ratingtravel',
            name='travel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourbooking.travel'),
        ),
        migrations.AddField(
            model_name='ratingtravel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
