# Generated by Django 3.2.6 on 2021-08-12 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourbooking', '0013_auto_20210812_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingtravel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
