# Generated by Django 3.2.6 on 2021-08-14 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourbooking', '0016_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tours',
            old_name='location',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='tours',
            old_name='detail_location',
            new_name='detail_destination',
        ),
        migrations.RemoveField(
            model_name='tours',
            name='address',
        ),
    ]
