# Generated by Django 3.2.6 on 2021-11-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourbooking', '0022_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='start_date',
            field=models.DateField(default='2021-01-01'),
            preserve_default=False,
        ),
    ]
