# Generated by Django 3.2.6 on 2021-11-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourbooking', '0023_tours_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_add',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_update',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tours',
            name='date_add',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tours',
            name='date_update',
            field=models.DateField(auto_now=True),
        ),
    ]
