# Generated by Django 3.2.6 on 2021-11-13 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tourbooking', '0026_tourimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingtour',
            name='content',
            field=models.TextField(default='Tour xuat sac', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratingtour',
            name='date_add',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratingtour',
            name='date_update',
            field=models.DateField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='ReviewTour',
        ),
    ]
