# Generated by Django 3.2.6 on 2021-11-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourbooking', '0027_auto_20211113_2159'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ratingtour',
            unique_together=set(),
        ),
    ]
