# Generated by Django 3.2.6 on 2021-11-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourbooking', '0028_alter_ratingtour_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingtour',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ratingtour',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
