# Generated by Django 3.2.6 on 2021-11-14 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourbooking', '0029_auto_20211114_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('adult', models.IntegerField()),
                ('children', models.IntegerField()),
                ('total', models.FloatField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourbooking.tours')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
