# Generated by Django 3.2.6 on 2021-11-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourbooking', '0030_ordertour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar-anonymous.png', upload_to='avatar/'),
        ),
    ]
