# Generated by Django 3.2.6 on 2021-11-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourbooking', '0033_auto_20211125_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/avatar-anonymous.png', max_length=200, upload_to='avatar/'),
        ),
    ]
