# Generated by Django 3.2.6 on 2021-11-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourbooking', '0034_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/avatar-anonymous.png', max_length=500, upload_to='avatar/'),
        ),
    ]
