# Generated by Django 3.2.6 on 2021-12-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourbooking', '0035_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='overview',
            field=models.TextField(default='News overview', max_length=1000),
            preserve_default=False,
        ),
    ]
